import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { FacebookPixelProvider } from '@/hooks/useFacebookPixel';

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
   children,
 }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={inter.className}>
    <FacebookPixelProvider>
      {children}
    </FacebookPixelProvider>
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.js"></script>
    </body>
    </html>
  );
}
